### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by addyosmani** [imgly/imgly-sdk-html5#120]
Leaving some feedback while using your great project to build an app:

* Demo: [HTML5 demos](https://github.com/imgly/imgly-sdk-html5/tree/master/examples) does not support selecting what device to use when taking pictures. On mobile, this makes usage tricky as by default the back camera is not used. We have a sample at [simpl.info](https://simpl.info/getusermedia/sources/) that shows how to use `MediaStreamTrack.getSources` to achieve this. Would make the current product demo much nicer :)
* Demo: I found the [comment](https://github.com/imgly/imgly-sdk-html5/blob/master/examples/canvas/application.js#L9) in the canvas demo confusing. Both it and the WebGL demo say that they default to WebGL and use canvas as a fallback, so I was left unsure what the difference between them was and assuming WebGL is always used if available. I believe what the canvas demo does is force `canvas` as the renderer but it may be better to tighten that comment text up.
* Docs: Unclear how best to integrate a custom build of `imgly-sdk-html5` into an existing project that already uses Gulp. I attempted three things:
  * `third_party` folder in my app with the full source from this repo that I customised. I then had to first have this folder be built before I could use it in my main app. Felt like it could be cleaner as there's a lot going on between dependencies, WebPack etc. 
  * Fork this repo. Only commit my final minified/custom 'theme' into my app, rather than the customised sources of `imgly-sdk-html5`. Again..unsure if this is how you saw folks using it.
  * What I ultimately settled on was actually just including the final (non-customised) `imgly-sdk-html5` files in my app and then using CSS selectors to override/customise everything. This works if you're fine with using DevTools to pluck out the right selectors, but probably isn't how you want folks using it. I think just telling folks what the best way to consume custom builds could be a great start. I probably spent a few hours wrangling to get the latest versions of project deps building on OSX vs. the much nicer experience of actually working with your library.
* Demo: Out of the box demo includes a "Imgly.ly Photo Editor SDK" text label in the examples when rendered. It's unclear if this needs to be kept in place for your licensing. I tried to use `showHeader` (from [here](https://github.com/imgly/imgly-sdk-html5/blob/master/src/js/ui/night/ui.js#L62)) to disable this but it wasn't working. In the end I had to use a CSS selector override to hide the text, but again I'm unsure if this is a licensing requirement or not. Might be useful to clarify somewhere what desired attribution is.
* Docs: I attempted to build a custom UI layer on top of `imgly-sdk-html5` but found that discovering how to trigger actions like taking a picture, file upload, switching to the editor view etc. outside of your default theme required a heavy read of the source. Thankfully it's well written/commented there, so it may be worth using something like JSDoc to output a readable online version to ease this being done.
* I'm building a high-performance app and noticed that calls to `https://www.photoeditorsdk.com/version.json?sdk=html5&jsoncallback=` for version checking add ~140ms to the network request time. I'm unsure what the call is actually doing and whether it's just there for analytics. Is this needed and is there a way to opt out of it being required? (short of manually editing source) :)

**Comment by sebastiandeutsch** [comment]
Thanks for taking time to give us feedback - it's really appreciated. We've gotten a little blind - especially at the docs. We'll try to fix these things as soon as possible.

**Comment by addyosmani** [comment]
Not at all! Thanks for considering the feedback :)

**Comment by saschagehlich** [comment]
Hey @addyosmani,

sorry for the (very) late reply - we've been very busy working on version 3 of PhotoEditorSDK which is now released: https://www.photoeditorsdk.com

We updated the docs and removed some of the confusing stuff you mentioned. I also added the other points to our list which will be resolved with one of the next releases.

Regarding the version.json hook: We're grabbing the latest version number from our web site so that we can notify the developers that their version is outdated. You can opt out using `versionCheck: false`

Thanks again for your feedback!

PS: We're closing issues in this repository, since version 3 is developed closed source.
