### ISSUE TITLE
Can quality of image shown on canvas be improved?

### ISSUE THREAD

**Issue by goneale** [imgly/imgly-sdk-html5#122]
Hi there,

Fantastic image processing component. I have just been doing some review and trialing a sample implementation, I found however that the image used for manipulation can appear quite pixalated in some instances, could it be an issue in how images are processed to resize or a webgl anti-aliasing issue?

The best example where the issue is quite apparent is when working with images containing text, or very high resolution images, two examples:
Example 1 - 500x300 image
![Example 1 - 500x300 image](https://sc-cdn.scaleengine.net/i/4d4617650f97f1983495bc5634af33a91.png)
Original image for ref - http://restaurantnews.com/wp-content/uploads/2012/10/East-Coast-Wings-Grill-Spreading-Its-Wings-in-Lexington-Signs-Deal-to-Open-Four-Local-Restaurants.jpg

Example 2 - 1651x952 image
![Example 2 - 1651x952 image](https://sc-cdn.scaleengine.net/i/76167f8930455a65310aa5ddba48ed45.png)
Original image for ref - http://www.ochrerestaurant.com.au/highres_images/ochre_outside.jpg
For example the sign post is very hard to read.

Perhaps it is with images of odd aspect ratios? As this image appears to render equal to original image - http://www.lachamade.com/wp-content/uploads/2013/11/table-restaurant.jpg

Where this particular becomes a problem for me is I have the user crop the image into a 21:9 aspect ratio prior to the image being loaded into this canvas, 9 times out of 10 this results in a jaggered or incorrect representation of the image.

Thanks a lot I appreciate any help you may offer on the issue.

**Comment by saschagehlich** [comment]
Hey @goneale,

thanks for your feedback. We just released version 3 which should have resolved the issue:

https://www.photoeditorsdk.com

Closing issues now, since version 3 is developed closed source. If you have any further questions, please use our slack channel (https://pesdk-slack.herokuapp.com/) or contact us via the contact form on our website!
