### ISSUE TITLE
Upper-left Crop can be dragged out of the canvas

### ISSUE THREAD

**Issue by schneyra** [imgly/imgly-sdk-html5#14]
While on the Crop-Screen, the upper-left corner of the crop-area can be dragged out of the canvas. Can be reproduced in the demo on sdk.img.ly

**Comment by saschagehlich** [comment]
Currently I'm focusing on the rewrite branch. This will be fixed with the new release which will probably land in mid february.

**Comment by saschagehlich** [comment]
The new SDK is ready to use (still in beta). The issue has been fixed.
