### ISSUE TITLE
No support for touch events

### ISSUE THREAD

**Issue by yaronuliel** [imgly/imgly-sdk-html5#15]
It seems to me like the library lacks support for touch event on mobile devices (and touch screen)
I think it is a very common need nowadays, and it will be very useful adding this support

Also, it shouldn't be that hard to do since you already support mouse events such as `mouseup`,`mousedown` and `mousemove` which in most cases can be added with the corresponding touch events

**Comment by saschagehlich** [comment]
I agree - I'm currently working on a rewrite of the SDK which will include touch support.

**Comment by saschagehlich** [comment]
@yaronuliel The new SDK is ready to use (still beta though) and has full touch support.
