### ISSUE TITLE
Save as on computer (button)

### ISSUE THREAD

**Issue by Stason77** [imgly/imgly-sdk-html5#17]
Hi guys!  Please,help me!  How make a SAVE button?  Аfter I will edit the image, i want  save a final image to my computer,how make a script for button?

Thank you!

**Comment by saschagehlich** [comment]
```js
imgly.renderToDataURL("png", { size: "300x300" }, function (err, dataUrl) {
  if (err) throw err;
  dataUrl = dataUrl.replace("image/png", "image/octet-stream");
  location.href = dataUrl;
});
```

**Comment by Stason77** [comment]
Thanks but i insert in code:

  // As soon as the user clicks the render button...
  // Listen for "Render final image" click
  renderButton.addEventListener("click", function (event) {
    var dataUrl;

    // dataUrl = imgly.renderToDataURL("png", function (err, dataUrl) {});
    // `dataUrl` now contains the full-sized rendered image
    // Caution: This string will probably exceed the maximum
    // dataURL size of 2M. You will not be able to set location.href
    // or an <img> tag's `src` attribute to this dataUrl.

    // dataUrl = imgly.renderToDataURL("png", { size: "100x100" }, function (err, dataUrl) {});
    // `dataUrl` now contains a resized rendered image that
    // does not exceed 100x100 while keeping the ratio

    // dataUrl = imgly.renderToDataURL("png", { size: "100x100!" }, function (err, dataUrl) {});
    // `dataUrl` now contains a resized rendered image with
    // a size of 100x100 pixels while _not_ keeping the ratio

    imgly.renderToDataURL("png", { size: "300x300" }, function (err, dataUrl) {



  if (err) throw err;
  dataUrl = dataUrl.replace("image/png", "image/octet-stream");
  location.href = dataUrl;




      // `dataUrl` now contains a resized rendered image with
      // a width of 300 pixels while keeping the ratio

      var image = document.createElement("img");
      image.setAttribute("src", dataUrl);
      document.getElementsByTagName("body")[0].appendChild(image);
    });
  });
};




and download image file without extension (not png or jpg) and this file i open & see only in browser(

**Comment by Stason77** [comment]
can I do something wrong? )  

want to when i press to click on the button "Render final image" ,open a window and i can (Save as) image file (png or jpg) any directory in my PC.


Thank you!

**Comment by saschagehlich** [comment]
https://code.google.com/p/download-data-uri/

**Comment by Stason77** [comment]
not work(   if it's so easy, may be you can do this button in example zip archive for download....

I think it is much more useful than social icons ;)

Thank you!!!! )
