### ISSUE TITLE
Resize mode?

### ISSUE THREAD

**Issue by neokiller** [imgly/imgly-sdk-html5#49]
Thank you for this wunderful plugin.

I wanted to use it in my backoffice website but it seems there is no resize (downgrade) dimension supported? It is possible to add this functionality?
I don't want to use Fotor and Aviary.... :-)

Thank you
Kind regards,

**Comment by saschagehlich** [comment]
Right now, there's no way to resize an image using the UI. The only way to resize the output picture is by providing image dimensions to the final `render()` function.
