### ISSUE TITLE
Question: any way to force an autocrop screen?

### ISSUE THREAD

**Issue by ganySA** [imgly/imgly-sdk-html5#50]
Hi

Thanks for this great library it really is awesome. Just one question is there any way to force the autocrop screen to popup when the library is first initiated?

**Comment by saschagehlich** [comment]
I just changed the NightUI API so that you can do something like this:

```js
kit.run();
kit.ui.switchToControl('crop');
```

This feature will be available with the next release, but you can also use the master branch to use it now.
