### ISSUE TITLE
Documentation: operationsStack docs

### ISSUE THREAD

**Issue by ganySA** [imgly/imgly-sdk-html5#51]
Hi

On the below page is a link to documentation that simply isnt working....
https://github.com/imgly/imgly-sdk-html5/blob/master/docs/tutorial/rendering-images-using-the-backend.md

Is there a link to operationsStack calls?

**Comment by saschagehlich** [comment]
There was a little bug in the documentation - `brightness` was set to 1.5, so the image that was rendered was completely white and invisible in the browser.

Please also note that you'll have to create and load `myImage` for this example to work, like this:

```js
var myImage = new Image();

myImage.addEventListener('load', function () {
 // imgly-sdk code goes here
});

myImage.src = 'test.jpg';
```
