### ISSUE TITLE
CORS problem with canvas

### ISSUE THREAD

**Issue by barsukov** [imgly/imgly-sdk-html5#56]
It is possible to have example with images which load by ur. Example
My url of image hosted on S3 and when I try to use filters I've got an error

```Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.```

The solution is here, but I do not know how to integrate it with your library.
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image?redirectlocale=en-US&redirectslug=CORS_Enabled_Image

**Comment by Stason77** [comment]
Владимир а Вы не знаете как реализовать сохранение отредактированного фото на пк пользователя? то есть сделать кнопку SAVE,чтобы при нажатии на фото сохранялось в виде hpg файла на компьютере пользователя... Заранее благодарю Вас.

**Comment by saschagehlich** [comment]
@barsukov There's two things you'll have to do: Add the `crossOrigin` attribute to the image that you're loading, like so:

```js
var image = new Image()
image.crossOrigin = 'Anonymous'
```

Also, the server you're fetching the image from needs to allow CORS for your domain, so it needs to respond with a `Access-Control-Allow-Origin` header.

@Stason77 The latest version (2.0.0-beta.10, just released it) has an optional export button.

**Comment by barsukov** [comment]
I have already found this solution too, but our service not allowed the cross origin , that the reason why it is a big deal. And I think this is so common thing. Do you have any ideas how it possible to avoid this problem.

**Comment by saschagehlich** [comment]
What you could do is write a proxy server that fetches the file from s3 and
serves it with the proper CORS header
