### ISSUE TITLE
how to add multi stickers

### ISSUE THREAD

**Issue by dcboy** [imgly/imgly-sdk-html5#62]
hi, i want to add multi stickers how to do?

**Comment by saschagehlich** [comment]
That's not possible right now. But we have plans to integrate this in the future.

**Comment by dcboy** [comment]
thx,
another question when i use android webview and select image then throw error undefine promise,
after i import promise v0.2.1 then alse throw another error  
"uncaught TypeError: Object function(){this.thenTargers=[],this.pending=!0} has no method 'all'

**Comment by dcboy** [comment]
![1](https://cloud.githubusercontent.com/assets/3503568/8480568/0340c876-2111-11e5-9f90-f4be1a5a96d9.jpg)
hello i have fix then problem but another have one , when i select a image the bottom of button is not enable,why?

**Comment by dcboy** [comment]
bug: in android webview 
<pre>
 var listItems = this._overviewControlsContainer.querySelectorAll(':scope > ul > li');
//listItems return length =0
</pre>

**Comment by dcboy** [comment]
android some version webview not support querySelectorAll(':scope

**Comment by dcboy** [comment]
hello bugfix
this._dom.background.remove()

fix to:
this._dom.background.parentNode.removeChild(this._dom.background);

**Comment by dcboy** [comment]
hello,how to fix the canvas width and hight?? for example i want to set the default size is 1:1 max width parent container

**Comment by dcboy** [comment]
how can i add custom photo frame on the canvas?
