### ISSUE TITLE
Imgly.sdk not compatible with Content Security Policy (CSP) 

### ISSUE THREAD

**Issue by barsukov** [imgly/imgly-sdk-html5#65]
Hello,

We have tried to run imgly.sdk with Content Security Policy (CSP) enabled. This is the used HTTP header:
```
Content-Security-Policy:default-src https: 'self'; connect-src https: 'self'; font-src https: 'self' data:; frame-src https: 'self'; img-src https: 'self' data:; media-src https: 'self'; object-src https: 'self'; script-src https: 'self'; style-src https: 'self';
```
Currently this is not compatible with your SDK. If you run it with this CSP settings you will receive the following errors: 

![screen shot]
(https://cloud.githubusercontent.com/assets/39571/9309126/f9096e06-4507-11e5-9740-bbebad4e6d5f.png)

We have tried to update the lodash library to avoid this error, but this error still occurred in other places.

For us CSP is must have requirement since we rely heavily on javascript functionality that should only be executed by authorized users.

Could you provide a version which is compatible with CSP?

**Comment by saschagehlich** [comment]
I updated the lodash version with a modern build. Please try the new version in the build folder of the master branch.

**Comment by barsukov** [comment]
Yes but lodash is not a one problem, We will update it too, but error still here. But I will try to use it too

**Comment by saschagehlich** [comment]
Lodash is the problem here, since it was dynamically creating and evaluating function code.

**Comment by barsukov** [comment]
Not only lodash has this error, probably dot.js as well give this error too, and another libraries. I will try with updated version, but I think this error will occur again.

**Comment by saschagehlich** [comment]
If it occurs again, please post another screenshot of the new error. I can only fix one error at a time since I don't have a CSP environment here.

**Comment by barsukov** [comment]
It is occur again, and at least 4 errors
in 4 different libraries and places

https://www.dropbox.com/s/7t1yz9cz0seh94k/Screenshot%202015-08-18%2017.39.37.png?dl=0

**Comment by saschagehlich** [comment]
The error you posted is occurring in dot.js which is in fact using eval. I'll work on template precompilation now to make sure eval is not being called. I'll let you know once this is done.

**Comment by saschagehlich** [comment]
I just pushed a new build to `master` which uses precompiled templates everywhere. I tested it on a CSP environment. Unfortunately we have some controls that use inline styling, since the UI elements are dynamic. E.g. you can add custom stickers to the stickers UI control and custom font faces to the font UI control using the API.

This means that it won't work with your `style-src https: 'self'` policy. Instead, you can use `style-src https: 'self' 'unsafe-inline'` which works fine.

**Comment by barsukov** [comment]
Thank you very much for very quick response, We have still error with your version checker.

![screenshot 2015-08-19 10 22 25](https://cloud.githubusercontent.com/assets/1594996/9351739/3b709206-465c-11e5-87b8-a9be76cab122.png)

About the inline styles, as long as this only affects stickers we will just disable stickers, and use without it.

**Comment by saschagehlich** [comment]
This also affects the Text operation, since the font buttons are also styled inline. But I just came up with an idea to avoid inline styles. I could just render small canvas elements into the UI. I'll work on this now.

Regarding the version check: I'll add an option to disable it.

**Comment by saschagehlich** [comment]
Done:

https://github.com/imgly/imgly-sdk-html5/releases/tag/v2.0.0-beta.18

I also added a `versionCheck` option. Set it to false to avoid a version check.

**Comment by barsukov** [comment]
Thank you for working this out. With a new build CSP is no longer an issue.

While we were tested it, we notice the stickers and text operation icons were too big.
<img width="1018" alt="screenshot 2015-08-19 13 50 04" src="https://cloud.githubusercontent.com/assets/1594996/9355423/6716692c-4679-11e5-928e-cc8d43960249.png">
<img width="1032" alt="screenshot 2015-08-19 13 50 16" src="https://cloud.githubusercontent.com/assets/1594996/9355422/670ea228-4679-11e5-9fd0-ff56268af815.png">

This occurred in Chrome and Firefox.

**Comment by saschagehlich** [comment]
I also made some changes to the CSS, you'll have to replace it.

**Comment by barsukov** [comment]
Thank you very much for your work, we updated and everything works fine.

**Comment by saschagehlich** [comment]
:+1:
