### ISSUE TITLE
Assets pipeline error in Ruby on Rails

### ISSUE THREAD

**Issue by barsukov** [imgly/imgly-sdk-html5#66]
Hi,

we are trying to include your SDK in a Ruby on Rails application. Rails since version 4.0 enhances every asset file name with fingerprints (a MD5 hash of the files content). This way all assets can be cached forever, since the content of a file will never change. Details can be found at http://guides.rubyonrails.org/asset_pipeline.html .

Imgly SDK references assets with a static filename (e.g. `ui/night/operations/crop.png`) for it's icons and stickers. This does not work for Rails with precompiled assets, since Rails will generate a file like `ui/night/operations/crop-bf4a75b66f4e4e1efacfc43fc82de0da.png`. Your editor will look like this:

![screenshot]
(https://cloud.githubusercontent.com/assets/651816/9270263/9862b59c-4270-11e5-88c3-ee8fd790b353.png)

Could you provide a way, to be compatible with the Rails asset pipeline?

One solution could be, to not reference images from javascript directly, but instead use css classes. The stylesheet than should reference the image or ideally include it directly as a base64 encoded image. A more advanced solution could be, to no longer rely on png images as icons, but instead use an icon font.

**Comment by saschagehlich** [comment]
Just don't put them in `app/assets/`, put them in `public` directly, bypassing the Asset Pipeline

**Comment by barsukov** [comment]
Yes, we have found a solution of this problem, but it is still workaround.

**Comment by krishan** [comment]
> Just don't put them in app/assets/, put them in public directly, bypassing the Asset Pipeline

For a single application, that is a good solution. 

But we are building a gem, and best practice for gems is to distribute the assets using `app/assets`, since gems do not have a `/public` folder of there own. Therefore we would much prefer a solution that would allow our gem to be a "good rails citizen" and provide the assets using the Asset Pipeline.

**Comment by saschagehlich** [comment]
Do you know how other plugins are handling this?

The only solution I can imagine is the following:

We could add an option `assetPathResolver` which is a function with a `path` parameter. The function can resolve the given path into another path which is then used in the SDK for all image assets. You would only have to get rails to generate a javascript map (original filename => filename with hash).

**Comment by krishan** [comment]
> Do you know how other plugins are handling this?

The usual approach is to rewrite all `JS` or `CSS` files using ERB and the `asset_path` helper, see: http://guides.rubyonrails.org/asset_pipeline.html#asset-organization. IMHO this is cumbersome and error prone. And it only works if the asset locations are static and fails in cases where the assets locations are calculated dynamically. 

> We could add an option assetPathResolver which is a function with a path parameter. 

I like this idea. It would allow us to integrate with the Asset Pipeline in a much easier and cleaner way.

**Comment by saschagehlich** [comment]
Is it possible to extract a map from the asset pipeline? I could of course give you a list of all requested assets and you could dynamically generate a map using `asset_path`...

**Comment by krishan** [comment]
> Is it possible to extract a map from the asset pipeline? 

Yes that should be possible for us by generating a JS file dynamically using ERB.

**Comment by saschagehlich** [comment]
I'll work on that feature now.

**Comment by saschagehlich** [comment]
I thought I already posted it here, but looks like I didn't. This feature has been added last night.

https://github.com/imgly/imgly-sdk-html5/commit/8c2054a0d5d40280a1cd74546594485d9d7df72a

**Comment by barsukov** [comment]
Thank you I will try with it.

**Comment by barsukov** [comment]
Yes we will try to integrate with rails, and this solution works good. Thank you. 

But only stickers not working correct, as you can see by screenshot. some sticker on the canvas not works. We disable stickers because it is not necessary functionality for us. Nevertheless I should report about it :smile: 

<img width="1017" alt="screenshot 2015-08-19 17 09 32" src="https://cloud.githubusercontent.com/assets/1594996/9360198/38852e42-4695-11e5-9121-ef982e320bb8.png">

**Comment by saschagehlich** [comment]
Thanks for reporting! Happy this solution works for you!
