### ISSUE TITLE
Loading message in top of left corner not going away.

### ISSUE THREAD

**Issue by barsukov** [imgly/imgly-sdk-html5#67]
One picture says more then 1000 words.
<img width="396" alt="screenshot 2015-08-31 11 57 58" src="https://cloud.githubusercontent.com/assets/1594996/9576384/8d4cabb2-4fd7-11e5-9233-4987995ec6dc.png">

This icon loading even the image has been loaded.

**Comment by saschagehlich** [comment]
Does it happen on the version that we integrated at photoeditorsdk.com as well?

**Comment by barsukov** [comment]
I took the latest version 2.0.0  stable and that was occurred afterwards. Should I show you my code examples.

**Comment by saschagehlich** [comment]
Yes please!

**Comment by barsukov** [comment]
https://gist.github.com/barsukov/15f3a4b6c67675132a4e#file-imgly-js

**Comment by saschagehlich** [comment]
Can you tell me the steps to reproduce this?

**Comment by saschagehlich** [comment]
Yup, there's a bug in the SDK. I've fixed it, releasing a hotfix now

**Comment by saschagehlich** [comment]
Fixed in `v2.0.0-2`:

https://github.com/imgly/imgly-sdk-html5/releases/tag/v2.0.0-2

Thanks for the report!

**Comment by barsukov** [comment]
Thank you for so quick fix! :+1:
