### ISSUE TITLE
"selectOperations()" Method cannot work!!

### ISSUE THREAD

**Issue by ryokanoshoh** [imgly/imgly-sdk-html5#68]
I can work Photo Editor SDK on Apache cordova by default.
I tried to "selectOperations()" method before "run()" but this method do now work
and force to stop before "run()".

If you have solve these problem, let me know.

Regards.

**Comment by ryokanoshoh** [comment]
According to web inspector of Safari, show this error message.
(see:snapshot)
<img width="820" alt="errorconsole" src="https://cloud.githubusercontent.com/assets/3196529/9707384/c90d1938-5541-11e5-9f17-8cc7ae786bce.png">
<img width="991" alt="errormsg" src="https://cloud.githubusercontent.com/assets/3196529/9707385/cd5d339c-5541-11e5-830e-8d7bfdd7fa7e.png">

**Comment by saschagehlich** [comment]
Try `kit.ui.selectOperations` instead

**Comment by ryokanoshoh** [comment]
Dear saschagehlich
Thank you for ask my question.
I tried to change "kit.ui.selectOperations".
I can handle the menu of operations.

Thank you.
Doumo arigatoh gozaimasu.(Japanese)
