### ISSUE TITLE
Issue while adding Text to the Image

### ISSUE THREAD

**Issue by pushpakpop** [imgly/imgly-sdk-html5#7]
First of all, Thank You for the awesome editor. I found a bug with the text input option. 

While adding text to the image, due to limited width of the Text-Input Container, the text wraps automatically inside the container. But when saved, the text is rendered in a single line and also text goes out of the screen. 

See the attached image.
![imgly-text-issue-1](https://cloud.githubusercontent.com/assets/4560461/3761855/d2eb8a06-188f-11e4-8602-e4d0a0e5c63b.png)
![imgly-text-issue-2](https://cloud.githubusercontent.com/assets/4560461/3761854/d2e9e32c-188f-11e4-9243-a40a7ccbc008.png)

**Comment by saschagehlich** [comment]
This has been fixed with the new SDK.
