### ISSUE TITLE
OSX 10.11.1: WebGL  Chrome Version 46.0.2490.80 (64-bit) - Zoomfunktion

### ISSUE THREAD

**Issue by madeleine-neumann** [imgly/imgly-sdk-html5#82]
Habe ein Bild in der Größe: 2835 × 1840px hochgeladen, konnte nicht weiter herein zoomen als 94% -> Gewollt?

**Comment by saschagehlich** [comment]
Gewollt! Maximales zoom level ist immer "Initiales Zoom Level (so dass es ganz sichtbar ist) * 2"
