### ISSUE TITLE
OSX 10.11.1: WebGL Safari Version 9.0.1 (11601.2.7.2): Anpassen des Fensters - Ruckelt

### ISSUE THREAD

**Issue by madeleine-neumann** [imgly/imgly-sdk-html5#83]
Wenn ich die Seite lade und das Fenster größer oder kleiner mache, braucht das Bild Ewigkeiten, bis es sich auf die Größe angepasst hat (es “hüpft” dann mit einem mal in die Browsergröße)

**Comment by saschagehlich** [comment]
Ist Absicht und leider nicht anders zu lösen. Die Reinitialisierung des Canvas dauert sehr lange, weshalb wir auch 1 Sekunde warten bis keine resize-events mehr kommen.
