### ISSUE TITLE
OSX 10.11.1: WebGL Safari Version 9.0.1 (11601.2.7.2): Text hinzufügen - Hüpfen

### ISSUE THREAD

**Issue by madeleine-neumann** [imgly/imgly-sdk-html5#85]
Füge ich einen Text hinzu, wird das Browserfenster für ne kurze Zeit schwarz und der zoom verändert sich. Zuvor ist das Bild bei 129%, beim hinzufügen “hüpft” es auf eine Größe von 99%. Das Selbe gilt für: Sticker/Frames/Crop

**Comment by saschagehlich** [comment]
Ist Absicht - während man diese Änderungen vornimmt, kann man das Bild nicht bewegen, deshalb haben wir uns dazu entschlossen, das Bild ganz anzuzeigen und Zoom und Pan zu deaktivieren
