### ISSUE TITLE
OSX 10.11.1: WebGL Safari Version 9.0.1 (11601.2.7.2): Bildexport

### ISSUE THREAD

**Issue by madeleine-neumann** [imgly/imgly-sdk-html5#87]
Klicke ich auf export, öffnet er mir das Bild nur im Browserfenster, es erfolgt kein Download. (Link zu dem Bild wäre: blob:http://static.9elements.com/aceef90f-e5c3-41a0-a8c5-c22091946f0e)

**Comment by saschagehlich** [comment]
Safari does not support the `download` attribute
