### ISSUE TITLE
OSX 10.11.1: WebGL Firefox Version 41.0.2 - Vergößerung/Verkleinerung Browserfenster 

### ISSUE THREAD

**Issue by madeleine-neumann** [imgly/imgly-sdk-html5#89]
Wenn ich die Seite lade und das Fenster größer oder kleiner mache, braucht das Bild Ewigkeiten, bis es sich auf die Größe angepasst hat (es “hüpft” dann mit einem mal in die Browsergröße)

**Comment by saschagehlich** [comment]
Duplicate of #83 - Not fixable
